baseURL: "https://opqrstuvcut.github.io"
canonifyURLs: true
relativeURLs: false

languageCode : "ja-jp"
theme: ["hugo-video", "terminal"]
# disqusShortname: https-opqrstuvcut-github-io-blog

pagination:
    pagerSize: 10
title: MatLoverによるMatlab以外のブログ  
hasCJKLanguage: true

DefaultContentLanguage: ja
enableInlineShortcodes: true
googleAnalytics: G-LFC5W8DKV1
publishDir: "docs"

permalinks:
    post: /posts/:slug/
    page: /:slug/

sitemap:
  filename: sitemap.xml

enableRobotsTXT: true

taxonomies:
  category: categories
  tag: tags

params:
    fullWidthTheme: true
    
    mainSections:
        - post
    featuredImageField: image
    # rssFullContent: true
    # favicon: ./static/favicon.ico
    # assets:
    #   favicon: favicon.ico

    footer:
        since: 2019

    widgets:
        homepage:
          - type: categories
            params:
                limit: 10
          - type: tag-cloud
            params:
                limit: 10
        # page:
        #   - type: toc
        #     params:

    # opengraph:
    #     twitter:
    #         # Your Twitter username
    #         site:
    #
    #         # Available values: summary, summary_large_image
    #         card: summary_large_image

    # defaultImage:
    #     opengraph:
    #         enabled: true 
    #         local: false
    #         src:

    # colorScheme:
    #     # Display toggle
    #     toggle: false
    #     
    #     # Available values: auto, light, dark
    #     default: light

    # imageProcessing:
    #     cover:
    #         enabled: true
    #     content:
    #         enabled: true
    # comments:
    #     enabled: true 
    #     provider: disqus

    contentTypeName: "post"
    showMenuItems: 10
    autoCover: false

languages:
  ja:
    params:
      title: MatLoverによるMatlab以外のブログ  
      menuMore: "Show more"
      readMore: "Read more"
      logo:
        logoText: MatLoverによるMatlab以外のブログ
    menu:
      - identifier: "about"
        name: "About"
        url: "/about"

menu:
    social:
        - identifier: github
          name: GitHub
          url: https://github.com/opqrstuvcut
          params:
              icon: brand-github

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    highlight:
        noClasses: false
    goldmark:
      extensions:
        passthrough:
          delimiters:
            block:
            - - \[
              - \]
            - - $$
              - $$
      renderer:
        unsafe: true
